### ISSUE TITLE
New error with the 24th of July update

### ISSUE THREAD

**Issue by Dainina** [Toludin/LunarSphere#3]
Hi!

Here's the new error i am getting today:

683x LunarSphere\lib\moduleButton.lua:7385: Usage: UnitBuff("unit", [index][, "filter"])
[C]: in function `UnitBuff'
LunarSphere\lib\moduleButton.lua:7385: in function `getBuffIndex'
LunarSphere\lib\moduleButton.lua:6322: in function `UpdateSpellState'
LunarSphere\lib\moduleButton.lua:5163: in function `?'
LunarSphere\lib\moduleButton.lua:5207: in function <LunarSphere\lib\moduleButton.lua:5205>

Locals:
(*temporary) = nil
(*temporary) = 1

**Comment by Toludin** [comment]
Thanks for the report! I assume you were on a hunter? Can you remember anything more about what triggered this error - or was it present on login and just always there? I see it shows 683 instances of that error in your report so I imagine it was somewhat constant.

**Comment by Dainina** [comment]
Yes, all i can really say is that it was doing it while i was moving around, standing still the error seemed to not trigger.

You are right, i do play a Hunter! I have some Hunter spells on Lunarsphere too(how did you know :O?).

I will look further into it tomorrow and update!

**Comment by Toludin** [comment]
Just pushed an update which I believe fixes the issue. The reason I knew you played hunter is that the stack trace shows the error came from a portion of the code which was handling Hunter Aspects - like, way back from when Aspects were stances. 

I removed the Hunter, DK and Paladin aura/aspect code, which I believe should be superfluous at this point since those classes no longer have stance-like spells. Initial testing showed no errors, but let me know if you run into any.

Thanks!

**Comment by Dainina** [comment]
I am receiving no errors! Everything seems to be working just fine, thank you!

**Comment by Toludin** [comment]
Glad to hear it, thanks for reporting this!
